### ISSUE TITLE
What are the steps to configuring the plugin after installation?

### ISSUE THREAD

**Issue by ystoneman** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#83]
I'm helping a customer transition away from hardcoding secrets in their Jenkins declarative pipeline to instead using Secrets Manager. Jenkins runs in a datacenter but this company also uses AWS. I see [in the docs](https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/master/docs/authentication/index.md) that AWS access keys and secret access keys are a supported alternative to roles.

I don't have admin rights to Jenkins...I only have access to code and AWS, so my customer tried installing it and reported back to me the following:
> I rolled back the secrets manager plugin thing. It has a requirement to have an IAM role, but our Jenkins is not in AWS and when Jenkins loaded after installing the plugin none of the credentials worked and our workers couldn't even connect and nothing could run. I rolled that back and Jenkins is healthy again, but we won't be able to use that plugin

I explained that the docs say that an IAM role isn't required.

My customer responded:
> probably won't use the plugin. Can we just use standard Jenkins credentials instead?
> this change brought all Jenkins down and I would have to deploy this off hours with no confidence it would get into working state and I don't see the benefit over standard jenkins credentials

So I wish that the docs for this plugin provided screenshots and/or code snippets for how to make it work without an IAM role (but with access keys and secret access keys instead). Since I don't have access in this account to see it myself and I don't have time to setup my own Jenkins instance, etc.

The setup portion of the docs only say, "Install and configure the plugin."

And the "Web UI" portion of the docs say:
> You can set plugin configuration using the Web UI.
> Go to Manage Jenkins > Configure System > AWS Secrets Manager Credentials Provider and change the settings.

But it does not give examples of what settings are available and how to configure them. Could those be added to the docs here?

**Comment by chriskilding** [comment]
Hi Yann,

When the plugin contacts AWS, it has to authenticate with AWS using one of the strategies. If Jenkins is hosted inside AWS then the most common thing is to use EC2 Instance Profiles, and then you grant the Jenkins principal the necessary permissions in its attached IAM policy.

If Jenkins is hosted outside AWS, as it is in your customer's case, then the plugin typically authenticates using an AWS access key pair which belongs to an IAM user. Although it's less obvious, IAM authorisation is still present in this use case, and still determines which resources the user can access. You'll need to grant the necessary permissions to the Jenkins IAM user which you have set up, by attaching a policy to it.

Once the permissions are in place, the plugin will start working. It can function even if there are no secrets in the account, in which case it just returns an empty list of credentials when asked.

Keep me posted on how this goes :)

**Comment by chriskilding** [comment]
I do agree that the README can be improved, so I can add the list of plugin config options to the relevant section.

If you need something quickly, the options in the Web UI are the same as the options that can be configured using CasC, which are shown just below it in the README.

**Comment by chriskilding** [comment]
The main motivation of using the Jenkins cloud plugins (including credentials providers like this, but also pluggable storage etc) is to make Jenkins as stateless as possible. This is of great benefit when Jenkins runs in cloud environments, where the underlying instance or container is ephemeral, and we want to share data with autoscaling Jenkins worker processes.

For traditional on-prem Jenkins installations, the Jenkins server tends to be built on stateful assumptions, and great effort usually goes into maximising the reliability and uptime of that server. As a result you don't gain so much benefit by externalising small amounts of config (like credentials) into AWS, because you still have the local server to maintain.

If your customer wants to **migrate** that Jenkins server to AWS, I would say it's worth moving to the Secrets Manager credentials provider; you can do this piecemeal, using AWS access key authentication while the server is on-prem, then shifting to Instance Profiles authentication after Jenkins is moved.

But if your customer only uses AWS 'on the side' and does not want to migrate Jenkins to the cloud, they may be better served by using the on-disk credentials provider, which was written for the use case of on-prem Jenkins servers.

**Comment by chriskilding** [comment]
Added a note about the fact that IAM is **always** present (even if you use an access key pair) to the README in https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/commit/2f5a13ec3a7ccbcc99de37ef82c2df9d266ef7c5
