### ISSUE TITLE
IAM permissions.

### ISSUE THREAD

**Issue by tjones-commits** [jenkinsci/aws-secrets-manager-credentials-provider-plugin#92]
I have tried searching through the other open issues but I could not find anything on this so let me know if this has already been covered. I am setting up jenkins on ecs fargate and I want to use this plugin to get secrets from secrets manager. I notice in the documentation that jenkins must be granted these iam permissions.

"secretsmanager:GetSecretValue" on resource *
"secretsmanager:ListSecrets"

This causes a problem for me because that grants the container access to all secrets in that account. I understand that the plugin can only get secrets that are tagged appropriately but there is nothing to prevent a developer from using the aws cli or api in a jenkins pipeline to access any credentials in secrets manager. Why does it need GetSecretValue on all secrets?

When I tried limiting the iam access to just the secrets required the plugin would not work.

Is there any workaround for this or am I just missing something? Any help is appreciated.

**Comment by chriskilding** [comment]
The problem is that ListSecrets is used to present the list of credentials in the API, which are then selected from and used by consuming plugins.  By default ListSecrets shows you *all* secrets in your account, not just the ones that your Jenkins IAM user can use.  However you can restrict this by setting the `filters` option on the plugin.

The only reason the README mentions `Resource`: `*` is to be on the safe side, to ensure that Jenkins can actually access the secrets it presents in case the user does not apply a filter. If you have success in applying restrictions to the GetSecretValue permission to make it more granular, then that's great - go with that.

**Comment by chriskilding** [comment]
I am a bit concerned that when you tried to limit the access to just the necessary secrets, it didn't work. That does sound like something that needs investigating. Can you follow the troubleshooting guide (linked in the README) and let me know what errors etc you can get from Jenkins?

**Comment by tjones-commits** [comment]
Thanks for getting back to me. One of my coworkers did a clean deployment and it worked when restricting the resources to just the required secrets for secretsmanager:GetSecretValue. So the problem could be something else with our AWS environment or how we configured the jenkins node. I am going to continue to experiment and I will let you know if I come up with anything that may be helpful.

Thanks for your help.

**Comment by chriskilding** [comment]
Just checking in, did you solve the problem in the end?

**Comment by tjones-commits** [comment]
I never figured it out one way or the other. I went with a different
solution. I was running Jenkins on ecs fargate so I added the secret arns
to the task definition so that the container would be launched with the
secrets.

I used the JCAC jenkins.yml file to create the secrets on the Jenkins side
